### ISSUE TITLE
Error when install with docker-ckan

### ISSUE THREAD

**Issue by mariorodeghiero** [okfn/ckanext-collaborators#18]
After install ckannext-collaborators I received this error on the terminal. 
Can be related and fix with this Patricio [PR #17 ](https://github.com/okfn/ckanext-collaborators/pull/17) ? 

**Command Runing :** 
- `docker-compose -f docker-compose.dev.yml up --build `

**Error:**

```
ckan-dev_1    | 2020-07-03 17:26:23,621 CRITI [ckanext.collaborators.plugin] 
ckan-dev_1    | The dataset collaborators extension requires a database setup. Please run the
ckan-dev_1    | following to create the database tables:
ckan-dev_1    |     paster --plugin=ckanext-collaborators collaborators init-db
ckan-dev_1    | 
solr          | 71795 INFO  (qtp1989972246-14) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*:*&rows=1&wt=json} hits=20 status=0 QTime=0
solr          | 71804 INFO  (qtp1989972246-21) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/admin/file params={file=schema.xml} status=0 QTime=0
ckan-dev_1    | 2020-07-03 17:26:23,689 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
ckan-dev_1    | Traceback (most recent call last):
ckan-dev_1    |   File "/usr/bin/paster", line 11, in <module>
ckan-dev_1    |     load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan-dev_1    |     invoke(command, command_name, options, args[1:])
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan-dev_1    |     exit_code = runner.run(args)
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan-dev_1    |     result = self.command()
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
ckan-dev_1    |     relative_to=base, global_conf=vars)
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
ckan-dev_1    |     **kw)
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
ckan-dev_1    |     return loadobj(APP, uri, name=name, **kw)
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
ckan-dev_1    |     return context.create()
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
ckan-dev_1    |     return self.object_type.invoke(self)
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
ckan-dev_1    |     return fix_call(context.object, context.global_conf, **context.local_conf)
ckan-dev_1    |   File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
ckan-dev_1    |     val = callable(*args, **kw)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 55, in make_app
ckan-dev_1    |     load_environment(conf, app_conf)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/config/environment.py", line 116, in load_environment
ckan-dev_1    |     p.load_all()
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 140, in load_all
ckan-dev_1    |     load(*plugins)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 168, in load
ckan-dev_1    |     plugins_update()
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 122, in plugins_update
ckan-dev_1    |     environment.update_config()
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/config/environment.py", line 305, in update_config
ckan-dev_1    |     logic.get_action('get_site_user')({'ignore_auth': True}, None)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/logic/__init__.py", line 435, in get_action
ckan-dev_1    |     name))
ckan-dev_1    | ckan.logic.NotFound: The action 'package_delete' is not found for chained action
docker-ckan_ckan-dev_1 exited with code 0
```

**Comment by pdelboca** [comment]
This error was happening because the container was running ckan `2.8.3` instead of the latest `2.8.4`.

The version of CKAN in `docker-ckan` was updated a [few months ago](https://github.com/okfn/docker-ckan/commit/1993b0f6c1d94fac44d575f9fa141091114f30e7) so if someone else is running into this error you need to rebuild the images: and [avoid docker cache](https://docs.docker.com/compose/reference/build/).
